const gradients = [
    "bg-gradient-to-r from-gray-600 to-gray-900",
    "bg-gradient-to-r from-gray-800 to-black",
    "bg-gradient-to-r from-gray-700 to-gray-900",
    "bg-gradient-to-r from-black to-gray-800",
    "bg-gradient-to-r from-gray-500 to-gray-800",
    "bg-gradient-to-r from-gray-900 to-black",
    "bg-gradient-to-r from-gray-700 to-black",
    "bg-gradient-to-r from-black to-gray-700",
    "bg-gradient-to-r from-gray-800 to-gray-900",
    "bg-gradient-to-r from-gray-600 to-black",
    "bg-gradient-to-r from-black to-gray-600",
    "bg-gradient-to-r from-gray-900 to-gray-700",
    "bg-gradient-to-r from-gray-700 to-gray-800",
    "bg-gradient-to-r from-black to-gray-900",
    "bg-gradient-to-r from-gray-800 to-gray-600",
    "bg-gradient-to-r from-gray-900 to-gray-800",
    "bg-gradient-to-r from-gray-600 to-gray-800",
    "bg-gradient-to-r from-black to-gray-500",
    "bg-gradient-to-r from-gray-800 to-gray-700",
    "bg-gradient-to-r from-gray-700 to-gray-600"
  ];